import type { SongDefinition } from "../game/types";

export const SONG_CATALOG: SongDefinition[] = [
  {
    id: "chromatic-run",
    title: "Chromatic Run",
    artist: "Neon Pulse Lab",
    category: "original",
    bpm: 128,
    duration: 23.5,
    subtitle: "原创 Web Audio 合成电子曲",
    synthProfile: "chromatic",
    accent: "cyan",
  },
  {
    id: "midnight-arcade",
    title: "Midnight Arcade",
    artist: "Neon Pulse Lab",
    category: "original",
    bpm: 102,
    duration: 52,
    subtitle: "原创低速碎拍与夜行合成波",
    synthProfile: "night-drive",
    accent: "violet",
  },
  {
    id: "beethoven-5-op67",
    title: "第五交响曲",
    englishTitle: "Symphony No. 5",
    artist: "路德维希·范·贝多芬",
    category: "classical",
    bpm: 108,
    duration: 72,
    subtitle: "短短短长动机驱动的铜管、弦乐与定音鼓改编",
    movement: "第一乐章 · Allegro con brio",
    workNumber: "作品 67",
    licenseLabel: "公版作品 · 本站原创合成改编",
    synthProfile: "beethoven-5",
    accent: "gold",
  },
  {
    id: "mozart-40-k550",
    title: "第四十交响曲",
    englishTitle: "Symphony No. 40",
    artist: "沃尔夫冈·阿马德乌斯·莫扎特",
    category: "classical",
    bpm: 132,
    duration: 68,
    subtitle: "敏捷弦乐与木管呼应的流动型主题改编",
    movement: "第一乐章 · Molto allegro",
    workNumber: "K.550",
    licenseLabel: "公版作品 · 本站原创合成改编",
    synthProfile: "mozart-40",
    accent: "rose",
  },
  {
    id: "dvorak-9-op95",
    title: "第九交响曲“自新大陆”",
    englishTitle: "Symphony No. 9 “From the New World”",
    artist: "安东宁·德沃夏克",
    category: "classical",
    bpm: 96,
    duration: 80,
    subtitle: "低音弦乐、铜管与定音鼓推进的戏剧化改编",
    movement: "第四乐章 · Allegro con fuoco",
    workNumber: "作品 95",
    licenseLabel: "公版作品 · 本站原创合成改编",
    synthProfile: "new-world",
    accent: "ember",
  },
  {
    id: "beethoven-9-op125",
    title: "第九交响曲“欢乐颂”",
    englishTitle: "Symphony No. 9 “Ode to Joy”",
    artist: "路德维希·范·贝多芬",
    category: "classical",
    bpm: 100,
    duration: 78,
    subtitle: "由简洁主题逐层叠加弦乐、木管与铜管的器乐改编",
    movement: "第四乐章 · 欢乐颂主题",
    workNumber: "作品 125",
    licenseLabel: "公版作品 · 本站原创合成改编",
    synthProfile: "ode-to-joy",
    accent: "azure",
  },
];

export const DEMO_SONG = SONG_CATALOG[0];

export const findSong = (songId: string) =>
  SONG_CATALOG.find((song) => song.id === songId);

